# Generated by Django 4.0a1 on 2021-10-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255)),
                ('expire_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
