# Generated by Django 4.0b1 on 2021-10-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyrelease', '0002_artist_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', to='spotifyrelease.Artist'),
        ),
    ]
